<a href="https://colab.research.google.com/github/Parul5789/ai-ml/blob/AIML/googlecolab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#System specification

In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
ad

In [ ]:
!cat /proc/meminfo

MemTotal:       13289424 kB
MemFree:         9693936 kB
MemAvailable:   12295120 kB
Buffers:          113268 kB
Cached:          2686712 kB
SwapCached:            0 kB
Active:           433048 kB
Inactive:        2940056 kB
Active(anon):       1380 kB
Inactive(anon):   573700 kB
Active(file):     431668 kB
Inactive(file):  2366356 kB
Unevictable:           8 kB
Mlocked:               8 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               352 kB
Writeback:             0 kB
AnonPages:        573284 kB
Mapped:           396928 kB
Shmem:              1948 kB
KReclaimable:      88200 kB
Slab:             124032 kB
SReclaimable:      88200 kB
SUnreclaim:        35832 kB
KernelStack:        5280 kB
PageTables:         8720 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6644712 kB
Committed_AS:    2722884 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       11892 kB
VmallocChunk:    

#library install and import

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/sample_data/california_housing_test.csv")

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0


# input var

In [ ]:
num1=int(input())
num2=int(input())
sum=num1+num2
print(sum)
print(num1)
print(num2)

23
12
35
23
12


In [ ]:
num1=int(input("enter the value"))

enter the value23


In [ ]:
type(num1)

int

(1+2j)
<class 'complex'>


#list tuple dict

In [ ]:
list = [1,2,3,4]
print(list)

[1, 2, 3, 4]


In [ ]:
list_1=[1,2,3,4]
list_2=[5,6,7,8,9]
del(list_1[2])
print(list_1)
list_3=list_1+list_2
print(list_3)

[1, 2, 4]
[1, 2, 4, 5, 6, 7, 8, 9]


In [ ]:
tuple_1=tuple(list_3)
print(tuple_1)

(1, 2, 4, 5, 6, 7, 8, 9)


In [ ]:
set1={1,2,3,2,3,4,5}
print(set1)

{1, 2, 3, 4, 5}


In [ ]:
ans=set(list_1)
print(ans)

{1, 2, 4}


In [ ]:
mydic={'name':'parul' , 'age':18 , 'name':'nisha'}
print(mydic)

{'name': 'nisha', 'age': 18}


In [ ]:
print(mydic['name'])

parul


In [ ]:
for i in mydic:
  print(i)


name
age


In [ ]:
for i in list_1 [1:2]:
  print(i);

2


In [ ]:
def fact(num):
  if num==0 or num==1:
    return 1
  else:
    return num*fact(num-1)

print(fact(5))

120


#numpy

In [ ]:
import numpy as np


In [ ]:
a=np.array([i for i in range(0,10)])
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
b=np.array([(1.0,3.1,4) , (4,5,6)],dtype=int)
print(b)

[[1 3 4]
 [4 5 6]]


In [ ]:
b.shape

(2, 3)

In [ ]:
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b=np.ones((2,3) , dtype=int)
print(b)

[[1 1 1]
 [1 1 1]]


In [ ]:
c=np.full((2,3),5)
print(c)

[[5 5 5]
 [5 5 5]]


In [ ]:
d=np.eye((3) , dtype=int)
print(d)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
e=np.random.random((3,4))

In [ ]:
print(e)

[[0.98477842 0.7311031  0.50716573 0.31283597]
 [0.12576434 0.30152725 0.67057641 0.89363866]
 [0.20057872 0.75064453 0.05040594 0.04676429]]


In [ ]:
f=np.random.randint(10,20,(3,4))
print(f)

[[12 17 19 19]
 [17 10 17 16]
 [10 19 16 13]]


In [ ]:
f=np.linspace(10,20,6)
print(f)

[10. 12. 14. 16. 18. 20.]


In [ ]:
f=np.arange(10,20,6)
print(f)

[10 16]


In [ ]:
l=[1,2,3,4]
g=np.asarray(l)


In [ ]:
print(g)

[1 2 3 4]


In [ ]:
type(g)

numpy.ndarray

In [ ]:
print(e.ndim)

2


In [ ]:
print(e.size)

12


In [ ]:
print(e)


[[0.42553194 0.5168935  0.32429484 0.06633084]
 [0.2459679  0.60281607 0.56736193 0.41690813]
 [0.07584898 0.58094807 0.39635282 0.71124724]]


In [ ]:
a=np.random.randint(10,20,(3,2))
b=np.random.randint(1,10,(3,2))
print(a)
print(b)
print(a+b)

[[19 16]
 [10 11]
 [11 19]]
[[1 8]
 [7 2]
 [7 2]]
[[20 24]
 [17 13]
 [18 21]]


In [ ]:
print(np.add(a,b))

[[20 24]
 [17 13]
 [18 21]]


In [ ]:
print(np.subtract(a,b))
print(np.multiply(a,b))

[[18  8]
 [ 3  9]
 [ 4 17]]
[[ 19 128]
 [ 70  22]
 [ 77  38]]


In [ ]:
print(np.transpose(a))



[[19 10 11]
 [16 11 19]]


In [ ]:
print(a.T)

[[19 10 11]
 [16 11 19]]


In [ ]:
a.reshape(2,3)
print(a)

[[19 16]
 [10 11]
 [11 19]]


#*Pandas

In [ ]:
import pandas as pd
